const Products = [
    {
      id: "1",
      Product: "https://m.media-amazon.com/images/I/61VuVU94RnL._AC_UY218_.jpg",
      Name : "IPhone 14",
      Category: "all,mobiles",
    },
    {
      id: "11",
      Product: "https://m.media-amazon.com/images/I/51Z-CqWUN1L._AC_UY218_.jpg",
      Name : "Acer i7",
      Category: "all,laptops",
    },
    {
      id: "21",
      Product: "https://m.media-amazon.com/images/I/511mMK0LW2L._AC_UY218_.jpg",
      Name : "Lenova tab7",
      Category: "all,tablets",
    },
    {
      id: "31",
      Product: "https://m.media-amazon.com/images/I/61WqF8Y6HTL._AC_UY218_.jpg",
      Name : "Boat Rockers270",
      Category: "all,headphones",
    },
    {
      id: "12",
      Product: "https://m.media-amazon.com/images/I/61Dw5Z8LzJL._AC_UY218_.jpg",
      Name : "Mi Book",
      Category: "all,laptops",
    },
    {
      id: "2",
      Product: "https://m.media-amazon.com/images/I/81t6Av5DvXL._AC_UY218_.jpg",
      Name : "Samsung M04",
      Category: "all,mobiles",
    },
    {
      id: "32",
      Product: "https://m.media-amazon.com/images/I/51i+LdztEBL._AC_UY218_.jpg",
      Name : "Sony U-7000",
      Category: "all,headphones",
    },
    {
      id: "22",
      Product: "https://m.media-amazon.com/images/I/81a-rN2A3DS._AC_UL320_.jpg",
      Name : "IPad ProMax",
      Category: "all,tablets",
    },
    {
      id: "33",
      Product: "https://m.media-amazon.com/images/I/61+btxzpfDL._AC_UY218_.jpg",
      Name : "Sony T-9000",
      Category: "all,headphones",
    },
    {
      id: "13",
      Product: "https://m.media-amazon.com/images/I/71tHNTGasKL._AC_UY218_.jpg",
      Name : "Lexgion Max",
      Category: "all,laptops",
    },
    {
      id: "23",
      Product: "https://m.media-amazon.com/images/I/71CKGX0iXPS._AC_UL320_.jpg",
      Name : "Samsung Tab 8",
      Category: "all,tablets",
    },
    {
      id: "3",
      Product: "https://m.media-amazon.com/images/I/81UT07JsBqL._AC_UY218_.jpg",
      Name : "Redmi A1",
      Category: "all,mobiles",
    },
    {
      id: "24",
      Product: "https://m.media-amazon.com/images/I/71UD5dhwyYS._AC_UL320_.jpg",
      Name : "Lenova Tab7",
      Category: "all,tablets",
    },
    {
      id: "5",
      Product: "https://m.media-amazon.com/images/I/61lKQWyMdDL._AC_UY218_.jpg",
      Name : "IPhone 14pro Max",
      Category: "all,mobiles",
    },
    {
      id: "34",
      Product: "https://m.media-amazon.com/images/I/81lLGM7SKbL._AC_UY218_.jpg",
      Name : "Zebronic 500",
      Category: "all,headphones",
    },
    {
      id: "14",
      Product: "https://m.media-amazon.com/images/I/810Y-PUrbyL._AC_UY218_.jpg",
      Name : "Hp Book pro",
      Category: "all,laptops",
    },
    {
      id: "6",
      Product: "https://m.media-amazon.com/images/I/81ZZPvIWnYL._AC_UY218_.jpg",
      Name : "Redmi Note 12",
      Category: "all,mobiles",
    },
    {
      id: "15",
      Product: "https://m.media-amazon.com/images/I/61Newaer7kS._AC_UY218_.jpg",
      Name : "Sony MaxBook",
      Category: "all,laptops",
    },
    {
      id: "25",
      Product: "https://m.media-amazon.com/images/I/61Eb9vtdSML._AC_UY218_.jpg",
      Name : "Redmi tabA",
      Category: "all,tablets",
    },
    {
      id: "35",
      Product: "https://m.media-amazon.com/images/I/61YHhQzV+KL._AC_UY218_.jpg",
      Name : "Sony Ultra",
      Category: "all,headphones",
    },
    {
      id: "16",
      Product: "https://m.media-amazon.com/images/I/71iiXU7HHkL._AC_UY218_.jpg",
      Name : "Mi NoteBook Pro",
      Category: "all,laptops",
    },
    {
      id: "36",
      Product: "https://m.media-amazon.com/images/I/61HXCeozUjL._AC_UY218_.jpg",
      Name : "JBL 2000",
      Category: "all,headphones",
    },
    {
      id: "7",
      Product: "https://m.media-amazon.com/images/I/81OZGH4fZiL._AC_UY218_.jpg",
      Name : "Redmi 10",
      Category: "all,mobiles",
    },
    {
      id: "26",
      Product: "https://m.media-amazon.com/images/I/41jdvXSoeyS._AC_UY218_.jpg",
      Name : "Lenova Tab X",
      Category: "all,tablets",
    },
    {
      id: "37",
      Product: "https://m.media-amazon.com/images/I/61LoZ5bkOkL._AC_UL320_.jpg",
      Name : "Magnet 2",
      Category: "all,headphones",
    },
    {
      id: "27",
      Product: "https://m.media-amazon.com/images/I/61R1tulpfzL._AC_UY218_.jpg",
      Name : "Samsung Tab7",
      Category: "all,tablets",
    },
    {
      id: "17",
      Product: "https://m.media-amazon.com/images/I/618M+ksuptL._AC_UY218_.jpg",
      Name : "Lexgion MaxBook",
      Category: "all,laptops",
    },
    {
      id: "8",
      Product: "https://m.media-amazon.com/images/I/61SpA599GgL._AC_UY218_.jpg",
      Name : "IQoo Z6",
      Category: "all,mobiles",
    },
    {
      id: "9",
      Product: "https://m.media-amazon.com/images/I/8104evx11QL._AC_UY218_.jpg",
      Name : "Oppo A78",
      Category: "all,mobiles",
    },
    {
      id: "18",
      Product: "https://m.media-amazon.com/images/I/71b8lYXqorL._AC_UY218_.jpg",
      Name : "Hp T-BU29785",
      Category: "all,laptops",
    },
    {
      id: "28",
      Product: "https://m.media-amazon.com/images/I/91veRYPjpeL._AC_UY218_.jpg",
      Name : "Samsung Tab A7",
      Category: "all,tablets",
    },
    {
      id: "39",
      Product: "https://m.media-amazon.com/images/I/51v35xHUkIL._AC_UL320_.jpg",
      Name : "Zebronic Loud",
      Category: "all,headphones",
    },
    {
      id: "19",
      Product: "https://m.media-amazon.com/images/I/61y-dK-6VhL._AC_UL320_.jpg",
      Name : "Hp TU3475",
      Category: "all,laptops",
    },
    {
      id: "40",
      Product: "https://m.media-amazon.com/images/I/61leGjTDm0L._AC_UY218_.jpg",
      Name : "Boat 9000",
      Category: "all,headphones",
    },
    {
      id: "29",
      Product: "https://m.media-amazon.com/images/I/51ZlTi5UKgL._AC_UY218_.jpg",
      Name : "Lenova Tab2",
      Category: "all,tablets",
    },
    {
      id: "10",
      Product: "https://m.media-amazon.com/images/I/61BGE6iu4AL._AC_UY218_.jpg",
      Name : "IPhone 13",
      Category: "all,mobiles",
    },
    {
      id: "20",
      Product: "https://m.media-amazon.com/images/I/91d75JiCH9L._AC_UY218_.jpg",
      Name : "Hp",
      Category: "all,laptops",
    },
    {
      id: "41",
      Product: "https://m.media-amazon.com/images/I/716Il5U5F4L._AC_UY218_.jpg",
      Name : "Info 2",
      Category: "all,headphones",
    },
    {
      id: "30",
      Product: "https://m.media-amazon.com/images/I/81Vs371KLML._AC_UY218_.jpg",
      Name : "Samsung Tab 5",
      Category: "all,tablets",
    },
    {
      id: "42",
      Product: "https://m.media-amazon.com/images/I/61HBpQuLjVL._AC_UY218_.jpg",
      Name : "Zebronic Mega",
      Category: "all,headphones",
    },
  ]

  export default Products;